# Generated by Django 2.1.2 on 2018-10-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='part_logo',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='partnerLogos'),
        ),
        migrations.AddField(
            model_name='partner',
            name='part_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
