# Generated by Django 2.1.2 on 2018-10-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181016_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='part_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='part_mission',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
